// Merchant registry for receipts extension.
// 200+ retailers across India, USA, Canada, UK.
// Each entry: { id, name, country, category, hostPattern, orderUrlPattern, status }
// status: 'planned' | 'extracting' | 'verified'
// Agents pick the next 'planned' entry and implement extraction logic.

export const MERCHANTS = [
  // ───────────────────────── INDIA ─────────────────────────
  // Marketplace
  { id: "amazon-in", name: "Amazon India", country: "IN", category: "marketplace", hostPattern: "https://www.amazon.in/*", orderUrlPattern: "/gp/your-account/order-details*", status: "planned" },
  { id: "flipkart", name: "Flipkart", country: "IN", category: "marketplace", hostPattern: "https://www.flipkart.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "myntra", name: "Myntra", country: "IN", category: "fashion", hostPattern: "https://www.myntra.com/*", orderUrlPattern: "/my/orders*", status: "planned" },
  { id: "ajio", name: "Ajio", country: "IN", category: "fashion", hostPattern: "https://www.ajio.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "meesho", name: "Meesho", country: "IN", category: "marketplace", hostPattern: "https://www.meesho.com/*", orderUrlPattern: "/orders*", status: "supported" },
  { id: "snapdeal", name: "Snapdeal", country: "IN", category: "marketplace", hostPattern: "https://www.snapdeal.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "tatacliq", name: "Tata CLiQ", country: "IN", category: "marketplace", hostPattern: "https://www.tatacliq.com/*", orderUrlPattern: "/my-account/orders*", status: "supported" },
  { id: "nykaa", name: "Nykaa", country: "IN", category: "beauty", hostPattern: "https://www.nykaa.com/*", orderUrlPattern: "/myaccount/orders*", status: "supported" },
  { id: "nykaa-fashion", name: "Nykaa Fashion", country: "IN", category: "fashion", hostPattern: "https://www.nykaafashion.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "firstcry", name: "FirstCry", country: "IN", category: "kids", hostPattern: "https://www.firstcry.com/*", orderUrlPattern: "/myorders*", status: "planned" },
  // Grocery / Quick commerce
  { id: "bigbasket", name: "BigBasket", country: "IN", category: "grocery", hostPattern: "https://www.bigbasket.com/*", orderUrlPattern: "/member/order*", status: "planned" },
  { id: "blinkit", name: "Blinkit", country: "IN", category: "quickcommerce", hostPattern: "https://blinkit.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "zepto", name: "Zepto", country: "IN", category: "quickcommerce", hostPattern: "https://www.zeptonow.com/*", orderUrlPattern: "/profile/orders*", status: "planned" },
  { id: "swiggy-instamart", name: "Swiggy Instamart", country: "IN", category: "quickcommerce", hostPattern: "https://www.swiggy.com/instamart*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "dunzo", name: "Dunzo", country: "IN", category: "quickcommerce", hostPattern: "https://www.dunzo.com/*", orderUrlPattern: "/orders*", status: "planned" },
  // Food delivery
  { id: "swiggy", name: "Swiggy", country: "IN", category: "food", hostPattern: "https://www.swiggy.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "zomato", name: "Zomato", country: "IN", category: "food", hostPattern: "https://www.zomato.com/*", orderUrlPattern: "/users/*/orders*", status: "supported" },
  // Electronics
  { id: "croma", name: "Croma", country: "IN", category: "electronics", hostPattern: "https://www.croma.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "reliance-digital", name: "Reliance Digital", country: "IN", category: "electronics", hostPattern: "https://www.reliancedigital.in/*", orderUrlPattern: "/myaccount/orders*", status: "planned" },
  { id: "vijay-sales", name: "Vijay Sales", country: "IN", category: "electronics", hostPattern: "https://www.vijaysales.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  // Pharmacy
  { id: "pharmeasy", name: "PharmEasy", country: "IN", category: "pharmacy", hostPattern: "https://pharmeasy.in/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "1mg", name: "1mg", country: "IN", category: "pharmacy", hostPattern: "https://www.1mg.com/*", orderUrlPattern: "/myorders*", status: "planned" },
  { id: "netmeds", name: "Netmeds", country: "IN", category: "pharmacy", hostPattern: "https://www.netmeds.com/*", orderUrlPattern: "/my-orders*", status: "planned" },
  { id: "apollo-pharmacy", name: "Apollo 24/7", country: "IN", category: "pharmacy", hostPattern: "https://www.apollopharmacy.in/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  // Travel
  { id: "makemytrip", name: "MakeMyTrip", country: "IN", category: "travel", hostPattern: "https://www.makemytrip.com/*", orderUrlPattern: "/mybiz/trips*", status: "planned" },
  { id: "goibibo", name: "Goibibo", country: "IN", category: "travel", hostPattern: "https://www.goibibo.com/*", orderUrlPattern: "/account/mytrips*", status: "planned" },
  { id: "ixigo", name: "Ixigo", country: "IN", category: "travel", hostPattern: "https://www.ixigo.com/*", orderUrlPattern: "/mytrips*", status: "planned" },
  { id: "yatra", name: "Yatra", country: "IN", category: "travel", hostPattern: "https://www.yatra.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "easemytrip", name: "EaseMyTrip", country: "IN", category: "travel", hostPattern: "https://www.easemytrip.com/*", orderUrlPattern: "/my-account/bookings*", status: "planned" },
  { id: "cleartrip", name: "Cleartrip", country: "IN", category: "travel", hostPattern: "https://www.cleartrip.com/*", orderUrlPattern: "/account/trips*", status: "planned" },
  { id: "irctc", name: "IRCTC", country: "IN", category: "travel", hostPattern: "https://www.irctc.co.in/*", orderUrlPattern: "/nget/booked-ticket-history*", status: "planned" },
  // Fashion / Lifestyle
  { id: "lifestyle", name: "Lifestyle", country: "IN", category: "fashion", hostPattern: "https://www.lifestylestores.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "shoppers-stop", name: "Shoppers Stop", country: "IN", category: "fashion", hostPattern: "https://www.shoppersstop.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "westside", name: "Westside", country: "IN", category: "fashion", hostPattern: "https://www.westside.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "puma-in", name: "Puma India", country: "IN", category: "fashion", hostPattern: "https://in.puma.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "nike-in", name: "Nike India", country: "IN", category: "fashion", hostPattern: "https://www.nike.com/in/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "adidas-in", name: "Adidas India", country: "IN", category: "fashion", hostPattern: "https://www.adidas.co.in/*", orderUrlPattern: "/account-orders*", status: "planned" },
  { id: "decathlon-in", name: "Decathlon India", country: "IN", category: "sports", hostPattern: "https://www.decathlon.in/*", orderUrlPattern: "/account/orders*", status: "planned" },
  // Home / Furniture
  { id: "urban-ladder", name: "Urban Ladder", country: "IN", category: "furniture", hostPattern: "https://www.urbanladder.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "pepperfry", name: "Pepperfry", country: "IN", category: "furniture", hostPattern: "https://www.pepperfry.com/*", orderUrlPattern: "/my-account*", status: "planned" },
  { id: "ikea-in", name: "IKEA India", country: "IN", category: "furniture", hostPattern: "https://www.ikea.com/in/*", orderUrlPattern: "/profile/orders*", status: "planned" },
  // Books
  { id: "bookswagon", name: "Bookswagon", country: "IN", category: "books", hostPattern: "https://www.bookswagon.com/*", orderUrlPattern: "/my-orders*", status: "planned" },
  // Pets
  { id: "heads-up-for-tails", name: "Heads Up For Tails", country: "IN", category: "pets", hostPattern: "https://www.headsupfortails.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  // Niche
  { id: "lenskart", name: "Lenskart", country: "IN", category: "eyewear", hostPattern: "https://www.lenskart.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "boat-lifestyle", name: "boAt Lifestyle", country: "IN", category: "electronics", hostPattern: "https://www.boat-lifestyle.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "mamaearth", name: "Mamaearth", country: "IN", category: "beauty", hostPattern: "https://mamaearth.in/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "purplle", name: "Purplle", country: "IN", category: "beauty", hostPattern: "https://www.purplle.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "limeroad", name: "LimeRoad", country: "IN", category: "fashion", hostPattern: "https://www.limeroad.com/*", orderUrlPattern: "/myaccount/orders*", status: "planned" },
  { id: "tira-beauty", name: "Tira Beauty", country: "IN", category: "beauty", hostPattern: "https://www.tirabeauty.com/*", orderUrlPattern: "/profile/orders*", status: "planned" },
  { id: "udaan", name: "Udaan", country: "IN", category: "marketplace", hostPattern: "https://udaan.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "country-delight", name: "Country Delight", country: "IN", category: "grocery", hostPattern: "https://www.countrydelight.in/*", orderUrlPattern: "/my-orders*", status: "planned" },
  // ──────────────────────── USA ────────────────────────
  { id: "amazon-us", name: "Amazon US", country: "US", category: "marketplace", hostPattern: "https://www.amazon.com/*", orderUrlPattern: "/gp/your-account/order-details*", status: "planned" },
  { id: "walmart", name: "Walmart", country: "US", category: "marketplace", hostPattern: "https://www.walmart.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "target", name: "Target", country: "US", category: "marketplace", hostPattern: "https://www.target.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "costco", name: "Costco", country: "US", category: "marketplace", hostPattern: "https://www.costco.com/*", orderUrlPattern: "/OrderStatusCmd*", status: "planned" },
  { id: "bestbuy", name: "Best Buy", country: "US", category: "electronics", hostPattern: "https://www.bestbuy.com/*", orderUrlPattern: "/profile/c/orders*", status: "planned" },
  { id: "ebay-us", name: "eBay US", country: "US", category: "marketplace", hostPattern: "https://www.ebay.com/*", orderUrlPattern: "/mye/myebay/purchase*", status: "planned" },
  { id: "etsy", name: "Etsy", country: "US", category: "marketplace", hostPattern: "https://www.etsy.com/*", orderUrlPattern: "/your/purchases*", status: "planned" },
  { id: "newegg", name: "Newegg", country: "US", category: "electronics", hostPattern: "https://www.newegg.com/*", orderUrlPattern: "/myaccount/orderhistory*", status: "planned" },
  { id: "wayfair", name: "Wayfair", country: "US", category: "furniture", hostPattern: "https://www.wayfair.com/*", orderUrlPattern: "/v/account/orders*", status: "planned" },
  { id: "homedepot", name: "Home Depot", country: "US", category: "home", hostPattern: "https://www.homedepot.com/*", orderUrlPattern: "/myaccount/orderhistory*", status: "planned" },
  { id: "lowes", name: "Lowe's", country: "US", category: "home", hostPattern: "https://www.lowes.com/*", orderUrlPattern: "/mylowes/orders*", status: "planned" },
  { id: "kohls", name: "Kohl's", country: "US", category: "fashion", hostPattern: "https://www.kohls.com/*", orderUrlPattern: "/myaccount/orderhistory*", status: "planned" },
  { id: "macys", name: "Macy's", country: "US", category: "fashion", hostPattern: "https://www.macys.com/*", orderUrlPattern: "/orderhistory*", status: "planned" },
  { id: "nordstrom", name: "Nordstrom", country: "US", category: "fashion", hostPattern: "https://www.nordstrom.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "sephora", name: "Sephora", country: "US", category: "beauty", hostPattern: "https://www.sephora.com/*", orderUrlPattern: "/profile/orders*", status: "planned" },
  { id: "ulta", name: "Ulta", country: "US", category: "beauty", hostPattern: "https://www.ulta.com/*", orderUrlPattern: "/order/history*", status: "planned" },
  { id: "nike-us", name: "Nike US", country: "US", category: "fashion", hostPattern: "https://www.nike.com/*", orderUrlPattern: "/orders/details*", status: "planned" },
  { id: "adidas-us", name: "Adidas US", country: "US", category: "fashion", hostPattern: "https://www.adidas.com/us/*", orderUrlPattern: "/account-orders*", status: "planned" },
  { id: "lululemon", name: "Lululemon", country: "US", category: "fashion", hostPattern: "https://shop.lululemon.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "gap", name: "Gap", country: "US", category: "fashion", hostPattern: "https://www.gap.com/*", orderUrlPattern: "/myaccount*", status: "planned" },
  { id: "oldnavy", name: "Old Navy", country: "US", category: "fashion", hostPattern: "https://oldnavy.gap.com/*", orderUrlPattern: "/myaccount*", status: "planned" },
  { id: "uniqlo-us", name: "Uniqlo US", country: "US", category: "fashion", hostPattern: "https://www.uniqlo.com/us/*", orderUrlPattern: "/order-history*", status: "planned" },
  { id: "zara-us", name: "Zara US", country: "US", category: "fashion", hostPattern: "https://www.zara.com/us/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "hm-us", name: "H&M US", country: "US", category: "fashion", hostPattern: "https://www2.hm.com/en_us/*", orderUrlPattern: "/myaccount/orders*", status: "planned" },
  { id: "asos-us", name: "ASOS US", country: "US", category: "fashion", hostPattern: "https://www.asos.com/us/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "shein-us", name: "SHEIN US", country: "US", category: "fashion", hostPattern: "https://us.shein.com/*", orderUrlPattern: "/user/orders*", status: "planned" },
  { id: "temu", name: "Temu", country: "US", category: "marketplace", hostPattern: "https://www.temu.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "aliexpress", name: "AliExpress", country: "US", category: "marketplace", hostPattern: "https://www.aliexpress.com/*", orderUrlPattern: "/p/order/index*", status: "planned" },
  { id: "wish", name: "Wish", country: "US", category: "marketplace", hostPattern: "https://www.wish.com/*", orderUrlPattern: "/transaction*", status: "planned" },
  // Food delivery USA
  { id: "doordash", name: "DoorDash", country: "US", category: "food", hostPattern: "https://www.doordash.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "ubereats-us", name: "Uber Eats US", country: "US", category: "food", hostPattern: "https://www.ubereats.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "grubhub", name: "Grubhub", country: "US", category: "food", hostPattern: "https://www.grubhub.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "postmates", name: "Postmates", country: "US", category: "food", hostPattern: "https://postmates.com/*", orderUrlPattern: "/orders*", status: "planned" },
  // Grocery USA
  { id: "instacart", name: "Instacart", country: "US", category: "grocery", hostPattern: "https://www.instacart.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "krogerus", name: "Kroger", country: "US", category: "grocery", hostPattern: "https://www.kroger.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "wholefoods", name: "Whole Foods", country: "US", category: "grocery", hostPattern: "https://www.wholefoodsmarket.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "traderjoes", name: "Trader Joe's", country: "US", category: "grocery", hostPattern: "https://www.traderjoes.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "safeway", name: "Safeway", country: "US", category: "grocery", hostPattern: "https://www.safeway.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  // Travel USA
  { id: "expedia-us", name: "Expedia", country: "US", category: "travel", hostPattern: "https://www.expedia.com/*", orderUrlPattern: "/trips*", status: "planned" },
  { id: "booking-us", name: "Booking.com", country: "US", category: "travel", hostPattern: "https://www.booking.com/*", orderUrlPattern: "/mybooking*", status: "planned" },
  { id: "airbnb-us", name: "Airbnb", country: "US", category: "travel", hostPattern: "https://www.airbnb.com/*", orderUrlPattern: "/trips*", status: "planned" },
  { id: "delta", name: "Delta Airlines", country: "US", category: "travel", hostPattern: "https://www.delta.com/*", orderUrlPattern: "/mytrips*", status: "planned" },
  { id: "united", name: "United Airlines", country: "US", category: "travel", hostPattern: "https://www.united.com/*", orderUrlPattern: "/en-us/manageReservations*", status: "planned" },
  { id: "southwest", name: "Southwest Airlines", country: "US", category: "travel", hostPattern: "https://www.southwest.com/*", orderUrlPattern: "/myaccount*", status: "planned" },
  { id: "american-airlines", name: "American Airlines", country: "US", category: "travel", hostPattern: "https://www.aa.com/*", orderUrlPattern: "/loyalty/mytrips*", status: "planned" },
  { id: "uber", name: "Uber", country: "US", category: "rideshare", hostPattern: "https://www.uber.com/*", orderUrlPattern: "/trips*", status: "planned" },
  { id: "lyft", name: "Lyft", country: "US", category: "rideshare", hostPattern: "https://account.lyft.com/*", orderUrlPattern: "/rides*", status: "planned" },
  // Books / Music
  { id: "barnesnoble", name: "Barnes & Noble", country: "US", category: "books", hostPattern: "https://www.barnesandnoble.com/*", orderUrlPattern: "/myaccount/orderhistory*", status: "planned" },
  // Pharmacy USA
  { id: "cvs", name: "CVS", country: "US", category: "pharmacy", hostPattern: "https://www.cvs.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "walgreens", name: "Walgreens", country: "US", category: "pharmacy", hostPattern: "https://www.walgreens.com/*", orderUrlPattern: "/youraccount/orderhistory*", status: "planned" },
  // Pet
  { id: "chewy", name: "Chewy", country: "US", category: "pets", hostPattern: "https://www.chewy.com/*", orderUrlPattern: "/app/account/orders*", status: "planned" },
  { id: "petco", name: "Petco", country: "US", category: "pets", hostPattern: "https://www.petco.com/*", orderUrlPattern: "/myaccount/orders*", status: "planned" },
  // Office
  { id: "staples", name: "Staples", country: "US", category: "office", hostPattern: "https://www.staples.com/*", orderUrlPattern: "/cc/mmx/order_history*", status: "planned" },
  // ──────────────────────── CANADA ────────────────────────
  { id: "amazon-ca", name: "Amazon Canada", country: "CA", category: "marketplace", hostPattern: "https://www.amazon.ca/*", orderUrlPattern: "/gp/your-account/order-details*", status: "planned" },
  { id: "walmart-ca", name: "Walmart Canada", country: "CA", category: "marketplace", hostPattern: "https://www.walmart.ca/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "costco-ca", name: "Costco Canada", country: "CA", category: "marketplace", hostPattern: "https://www.costco.ca/*", orderUrlPattern: "/OrderStatusCmd*", status: "planned" },
  { id: "canadian-tire", name: "Canadian Tire", country: "CA", category: "marketplace", hostPattern: "https://www.canadiantire.ca/*", orderUrlPattern: "/en/order-history*", status: "planned" },
  { id: "loblaws", name: "Loblaws", country: "CA", category: "grocery", hostPattern: "https://www.loblaws.ca/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "shoppers-drug-mart", name: "Shoppers Drug Mart", country: "CA", category: "pharmacy", hostPattern: "https://www.shoppersdrugmart.ca/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "indigo", name: "Indigo", country: "CA", category: "books", hostPattern: "https://www.indigo.ca/*", orderUrlPattern: "/en-ca/account/order-history*", status: "planned" },
  { id: "best-buy-ca", name: "Best Buy Canada", country: "CA", category: "electronics", hostPattern: "https://www.bestbuy.ca/*", orderUrlPattern: "/profile/orderhistory*", status: "planned" },
  { id: "the-bay", name: "The Bay", country: "CA", category: "fashion", hostPattern: "https://www.thebay.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "sportchek", name: "Sport Chek", country: "CA", category: "sports", hostPattern: "https://www.sportchek.ca/*", orderUrlPattern: "/order-history*", status: "planned" },
  { id: "mec", name: "MEC", country: "CA", category: "sports", hostPattern: "https://www.mec.ca/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "lululemon-ca", name: "Lululemon Canada", country: "CA", category: "fashion", hostPattern: "https://shop.lululemon.com/en-ca/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "winners", name: "Winners", country: "CA", category: "fashion", hostPattern: "https://www.winners.ca/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "homedepot-ca", name: "Home Depot Canada", country: "CA", category: "home", hostPattern: "https://www.homedepot.ca/*", orderUrlPattern: "/myaccount/orderhistory*", status: "planned" },
  { id: "rona", name: "RONA", country: "CA", category: "home", hostPattern: "https://www.rona.ca/*", orderUrlPattern: "/en/orders*", status: "planned" },
  { id: "ikea-ca", name: "IKEA Canada", country: "CA", category: "furniture", hostPattern: "https://www.ikea.com/ca/*", orderUrlPattern: "/profile/orders*", status: "planned" },
  { id: "structube", name: "Structube", country: "CA", category: "furniture", hostPattern: "https://www.structube.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "sephora-ca", name: "Sephora Canada", country: "CA", category: "beauty", hostPattern: "https://www.sephora.com/ca/*", orderUrlPattern: "/profile/orders*", status: "planned" },
  { id: "lcbo", name: "LCBO", country: "CA", category: "alcohol", hostPattern: "https://www.lcbo.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "saq", name: "SAQ", country: "CA", category: "alcohol", hostPattern: "https://www.saq.com/*", orderUrlPattern: "/en/account/orders*", status: "planned" },
  { id: "skipthedishes", name: "SkipTheDishes", country: "CA", category: "food", hostPattern: "https://www.skipthedishes.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "doordash-ca", name: "DoorDash Canada", country: "CA", category: "food", hostPattern: "https://www.doordash.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "ubereats-ca", name: "Uber Eats Canada", country: "CA", category: "food", hostPattern: "https://www.ubereats.com/ca/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "instacart-ca", name: "Instacart Canada", country: "CA", category: "grocery", hostPattern: "https://www.instacart.ca/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "metro-ca", name: "Metro", country: "CA", category: "grocery", hostPattern: "https://www.metro.ca/*", orderUrlPattern: "/order-history*", status: "planned" },
  { id: "sobeys", name: "Sobeys", country: "CA", category: "grocery", hostPattern: "https://www.sobeys.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "no-frills", name: "No Frills", country: "CA", category: "grocery", hostPattern: "https://www.nofrills.ca/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "longos", name: "Longo's", country: "CA", category: "grocery", hostPattern: "https://www.longos.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "westjet", name: "WestJet", country: "CA", category: "travel", hostPattern: "https://www.westjet.com/*", orderUrlPattern: "/manage-trips*", status: "planned" },
  { id: "air-canada", name: "Air Canada", country: "CA", category: "travel", hostPattern: "https://www.aircanada.com/*", orderUrlPattern: "/aeroplan/manage-bookings*", status: "planned" },
  { id: "expedia-ca", name: "Expedia Canada", country: "CA", category: "travel", hostPattern: "https://www.expedia.ca/*", orderUrlPattern: "/trips*", status: "planned" },
  // ──────────────────────── UK ────────────────────────
  { id: "amazon-uk", name: "Amazon UK", country: "UK", category: "marketplace", hostPattern: "https://www.amazon.co.uk/*", orderUrlPattern: "/gp/your-account/order-details*", status: "planned" },
  { id: "argos", name: "Argos", country: "UK", category: "marketplace", hostPattern: "https://www.argos.co.uk/*", orderUrlPattern: "/myaccount/orders*", status: "planned" },
  { id: "johnlewis", name: "John Lewis", country: "UK", category: "marketplace", hostPattern: "https://www.johnlewis.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "marksandspencer", name: "Marks & Spencer", country: "UK", category: "marketplace", hostPattern: "https://www.marksandspencer.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "next-uk", name: "Next", country: "UK", category: "fashion", hostPattern: "https://www.next.co.uk/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "boots", name: "Boots", country: "UK", category: "pharmacy", hostPattern: "https://www.boots.com/*", orderUrlPattern: "/your-account/orders*", status: "planned" },
  { id: "superdrug", name: "Superdrug", country: "UK", category: "pharmacy", hostPattern: "https://www.superdrug.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "currys", name: "Currys", country: "UK", category: "electronics", hostPattern: "https://www.currys.co.uk/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "ao-com", name: "AO.com", country: "UK", category: "electronics", hostPattern: "https://ao.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "very", name: "Very", country: "UK", category: "marketplace", hostPattern: "https://www.very.co.uk/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "littlewoods", name: "Littlewoods", country: "UK", category: "marketplace", hostPattern: "https://www.littlewoods.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "asos-uk", name: "ASOS UK", country: "UK", category: "fashion", hostPattern: "https://www.asos.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "boohoo", name: "Boohoo", country: "UK", category: "fashion", hostPattern: "https://www.boohoo.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "prettylittlething", name: "PrettyLittleThing", country: "UK", category: "fashion", hostPattern: "https://www.prettylittlething.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "missguided", name: "Missguided", country: "UK", category: "fashion", hostPattern: "https://www.missguided.co.uk/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "newlook-uk", name: "New Look", country: "UK", category: "fashion", hostPattern: "https://www.newlook.com/uk/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "river-island", name: "River Island", country: "UK", category: "fashion", hostPattern: "https://www.riverisland.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "topshop", name: "Topshop", country: "UK", category: "fashion", hostPattern: "https://www.topshop.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "primark", name: "Primark", country: "UK", category: "fashion", hostPattern: "https://www.primark.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "matalan", name: "Matalan", country: "UK", category: "fashion", hostPattern: "https://www.matalan.co.uk/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "zara-uk", name: "Zara UK", country: "UK", category: "fashion", hostPattern: "https://www.zara.com/uk/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "hm-uk", name: "H&M UK", country: "UK", category: "fashion", hostPattern: "https://www2.hm.com/en_gb/*", orderUrlPattern: "/myaccount/orders*", status: "planned" },
  { id: "uniqlo-uk", name: "Uniqlo UK", country: "UK", category: "fashion", hostPattern: "https://www.uniqlo.com/uk/*", orderUrlPattern: "/order-history*", status: "planned" },
  { id: "shein-uk", name: "SHEIN UK", country: "UK", category: "fashion", hostPattern: "https://uk.shein.com/*", orderUrlPattern: "/user/orders*", status: "planned" },
  { id: "ebay-uk", name: "eBay UK", country: "UK", category: "marketplace", hostPattern: "https://www.ebay.co.uk/*", orderUrlPattern: "/mye/myebay/purchase*", status: "planned" },
  { id: "etsy-uk", name: "Etsy UK", country: "UK", category: "marketplace", hostPattern: "https://www.etsy.com/uk/*", orderUrlPattern: "/your/purchases*", status: "planned" },
  // Grocery UK
  { id: "tesco", name: "Tesco", country: "UK", category: "grocery", hostPattern: "https://www.tesco.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "sainsburys", name: "Sainsbury's", country: "UK", category: "grocery", hostPattern: "https://www.sainsburys.co.uk/*", orderUrlPattern: "/groceries/orders*", status: "planned" },
  { id: "asda", name: "ASDA", country: "UK", category: "grocery", hostPattern: "https://groceries.asda.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "morrisons", name: "Morrisons", country: "UK", category: "grocery", hostPattern: "https://groceries.morrisons.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "waitrose", name: "Waitrose", country: "UK", category: "grocery", hostPattern: "https://www.waitrose.com/*", orderUrlPattern: "/ecom/myaccount*", status: "planned" },
  { id: "iceland-uk", name: "Iceland", country: "UK", category: "grocery", hostPattern: "https://www.iceland.co.uk/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "ocado", name: "Ocado", country: "UK", category: "grocery", hostPattern: "https://www.ocado.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "lidl-uk", name: "Lidl UK", country: "UK", category: "grocery", hostPattern: "https://www.lidl.co.uk/*", orderUrlPattern: "/account/orders*", status: "planned" },
  // Food delivery UK
  { id: "deliveroo", name: "Deliveroo", country: "UK", category: "food", hostPattern: "https://deliveroo.co.uk/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "justeat-uk", name: "Just Eat", country: "UK", category: "food", hostPattern: "https://www.just-eat.co.uk/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "ubereats-uk", name: "Uber Eats UK", country: "UK", category: "food", hostPattern: "https://www.ubereats.com/gb/*", orderUrlPattern: "/orders*", status: "planned" },
  // Travel UK
  { id: "british-airways", name: "British Airways", country: "UK", category: "travel", hostPattern: "https://www.britishairways.com/*", orderUrlPattern: "/travel/managemybooking*", status: "planned" },
  { id: "easyjet", name: "easyJet", country: "UK", category: "travel", hostPattern: "https://www.easyjet.com/*", orderUrlPattern: "/managebookings*", status: "planned" },
  { id: "ryanair", name: "Ryanair", country: "UK", category: "travel", hostPattern: "https://www.ryanair.com/*", orderUrlPattern: "/account/bookings*", status: "planned" },
  { id: "expedia-uk", name: "Expedia UK", country: "UK", category: "travel", hostPattern: "https://www.expedia.co.uk/*", orderUrlPattern: "/trips*", status: "planned" },
  { id: "booking-uk", name: "Booking.com UK", country: "UK", category: "travel", hostPattern: "https://www.booking.com/*", orderUrlPattern: "/mybooking*", status: "planned" },
  { id: "airbnb-uk", name: "Airbnb UK", country: "UK", category: "travel", hostPattern: "https://www.airbnb.co.uk/*", orderUrlPattern: "/trips*", status: "planned" },
  { id: "thetrainline", name: "Trainline", country: "UK", category: "travel", hostPattern: "https://www.thetrainline.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  // Home / Furniture UK
  { id: "ikea-uk", name: "IKEA UK", country: "UK", category: "furniture", hostPattern: "https://www.ikea.com/gb/*", orderUrlPattern: "/profile/orders*", status: "planned" },
  { id: "wayfair-uk", name: "Wayfair UK", country: "UK", category: "furniture", hostPattern: "https://www.wayfair.co.uk/*", orderUrlPattern: "/v/account/orders*", status: "planned" },
  { id: "made-com", name: "MADE.com", country: "UK", category: "furniture", hostPattern: "https://www.made.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "dunelm", name: "Dunelm", country: "UK", category: "home", hostPattern: "https://www.dunelm.com/*", orderUrlPattern: "/customer/orders*", status: "planned" },
  { id: "wilko", name: "Wilko", country: "UK", category: "home", hostPattern: "https://www.wilko.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "screwfix", name: "Screwfix", country: "UK", category: "home", hostPattern: "https://www.screwfix.com/*", orderUrlPattern: "/jsp/myaccount/orderhistory*", status: "planned" },
  { id: "bandq", name: "B&Q", country: "UK", category: "home", hostPattern: "https://www.diy.com/*", orderUrlPattern: "/customer/orders*", status: "planned" },
  // Books UK
  { id: "waterstones", name: "Waterstones", country: "UK", category: "books", hostPattern: "https://www.waterstones.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  { id: "wob", name: "World of Books", country: "UK", category: "books", hostPattern: "https://www.wob.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
  // Beauty UK
  { id: "lookfantastic", name: "Lookfantastic", country: "UK", category: "beauty", hostPattern: "https://www.lookfantastic.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "cult-beauty", name: "Cult Beauty", country: "UK", category: "beauty", hostPattern: "https://www.cultbeauty.co.uk/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "feel-unique", name: "FeelUnique", country: "UK", category: "beauty", hostPattern: "https://www.feelunique.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "the-body-shop-uk", name: "The Body Shop UK", country: "UK", category: "beauty", hostPattern: "https://www.thebodyshop.com/en-gb/*", orderUrlPattern: "/account/orders*", status: "planned" },
  // Pet UK
  { id: "petsathome", name: "Pets at Home", country: "UK", category: "pets", hostPattern: "https://www.petsathome.com/*", orderUrlPattern: "/my-account/orders*", status: "planned" },
  { id: "zooplus-uk", name: "Zooplus UK", country: "UK", category: "pets", hostPattern: "https://www.zooplus.co.uk/*", orderUrlPattern: "/account/orders*", status: "planned" },
  // Office UK
  { id: "ryman", name: "Ryman", country: "UK", category: "office", hostPattern: "https://www.ryman.co.uk/*", orderUrlPattern: "/account/orders*", status: "planned" },
  // Tech / Specialist
  { id: "scan", name: "Scan", country: "UK", category: "electronics", hostPattern: "https://www.scan.co.uk/*", orderUrlPattern: "/customer/orders*", status: "planned" },
  { id: "overclockers", name: "Overclockers UK", country: "UK", category: "electronics", hostPattern: "https://www.overclockers.co.uk/*", orderUrlPattern: "/customer/account/orders*", status: "planned" },
  { id: "ebuyer", name: "Ebuyer", country: "UK", category: "electronics", hostPattern: "https://www.ebuyer.com/*", orderUrlPattern: "/orders*", status: "planned" },
  { id: "costco-uk", name: "Costco UK", country: "UK", category: "marketplace", hostPattern: "https://www.costco.co.uk/*", orderUrlPattern: "/OrderStatusCmd*", status: "planned" },
  { id: "selfridges", name: "Selfridges", country: "UK", category: "fashion", hostPattern: "https://www.selfridges.com/*", orderUrlPattern: "/account/orders*", status: "planned" },
];

export const MERCHANTS_BY_ID = Object.fromEntries(MERCHANTS.map((m) => [m.id, m]));
export const MERCHANTS_BY_COUNTRY = MERCHANTS.reduce((acc, m) => {
  (acc[m.country] ||= []).push(m);
  return acc;
}, {});
